### ISSUE TITLE
MySQL connect error

### ISSUE THREAD

**Issue by Tourin** [Mitsugaru/PlayerPoints#15] opened 2016-05-09 08:01 UTC
java.lang.NoClassDefFoundError: lib/PatPeter/SQLibrary/MySQL
        at org.black_ixx.playerpoints.storage.models.MySQLStorage.connect(MySQLStorage.java:276) ~[?:?]
        at org.black_ixx.playerpoints.storage.models.MySQLStorage.<init>(MySQLStorage.java:61) ~[?:?]
        at org.black_ixx.playerpoints.storage.StorageGenerator.createStorageHandlerForType(StorageGenerator.java:47) ~[?:?]
        at org.black_ixx.playerpoints.storage.StorageHandler.starting(StorageHandler.java:65) ~[?:?]
        at org.black_ixx.playerpoints.PlayerPoints.registerModule(PlayerPoints.java:139) ~[?:?]
        at org.black_ixx.playerpoints.PlayerPoints.onEnable(PlayerPoints.java:64) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: lib.PatPeter.SQLibrary.MySQL
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-latest.jar:git-Spigot-e6f93f4-935f18b]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
        ... 17 more

**Comment by Mitsugaru** [comment] 2016-05-09 14:43
Duplicate of #13 
> You are missing the [SQLibrary](http://dev.bukkit.org/bukkit-plugins/sqlibrary/) dependency. If you want MySQL support, you need to add the library to your plugins folder.

**Closed by Mitsugaru** 2016-05-09 14:43 UTC

**Comment by BurkenDev** [comment] 2021-02-18 18:06
Why not just use the regular built in java mysql library? Then there would be no need to even have an extra separate library unneccessarily.
